### ISSUE TITLE
error happening when checking for in-app notifications when no day mood has been yet set

### ISSUE THREAD

**Issue by kairos666** [kairos666/moodys#31]
**How to reproduce** Each day when no mood has been yet set it appears consistently in home page

**store.js**: let moodToNotif = Object.keys(newDayMoods).map(uid => newDayMoods[uid])
        .filter(dayMoods => (dayMoods.timestamp > thresholdTimestamp));

**traces FIREBASE warning**
util.js:233 FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at https://moodies-1ad4f.firebaseapp.com/static/js/app.b83c8425c4017c1da978.js:1:5554
    at https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:378:746
    at e.exceptionGuard (https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:7:6483)
    at t.raise (https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:375:1334)
    at t.raiseQueuedEventsMatchingPredicate_ (https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:375:895)
    at t.raiseEventsForChangedPath (https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:375:609)
    at Object.<anonymous> (https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:72:2116)
    at https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:163:2971
    at e.onDataMessage_ (https://moodies-1ad4f.firebaseapp.com/static/js/vendor.0ed8196a97af4390bba4.js:163:6651) 
e.warn @ util.js:233

**traces app error**
util.js:586 Uncaught TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at store.js:102
    at EventRegistration.js:77
    at e.exceptionGuard (util.js:576)
    at t.raise (EventQueue.js:167)
    at t.raiseQueuedEventsMatchingPredicate_ (EventQueue.js:106)
    at t.raiseEventsForChangedPath (EventQueue.js:90)
    at Object.<anonymous> (Repo.js:144)
    at PersistentConnection.js:223
    at e.onDataMessage_ (PersistentConnection.js:461)

**Comment by kairos666** [comment]
fix waiting to be merged
